import type { PdfSettings } from "./types";

export interface PdfTemplate {
  id: string;
  name: string;
  description: string;
  thumbnail: string; // emoji or icon key
  settings: Partial<PdfSettings>;
}

export const PDF_TEMPLATES: PdfTemplate[] = [
  {
    id: "dark-premium",
    name: "Dark Premium",
    description: "Fundo escuro com acentos roxos, visual sofisticado",
    thumbnail: "🌙",
    settings: {
      background_color: "#0B0D12",
      accent_color: "#7C5CFF",
      title_color: "#FFFFFF",
      subtitle_color: "#A0A4B8",
      margin_size: 60,
      title_font_size: 32,
      subtitle_font_size: 18,
      card_image_width_pct: 45,
      card_font_size: 14,
      card_date_font_size: 12,
      card_caption_font_size: 11,
      carousel_cols: 4,
      carousel_rows: 2,
      carousel_image_height_pct: 65,
    },
  },
  {
    id: "clean-white",
    name: "Clean White",
    description: "Fundo branco minimalista com acentos azuis",
    thumbnail: "☀️",
    settings: {
      background_color: "#FAFAFA",
      accent_color: "#2563EB",
      title_color: "#111827",
      subtitle_color: "#6B7280",
      margin_size: 70,
      title_font_size: 30,
      subtitle_font_size: 16,
      card_image_width_pct: 48,
      card_font_size: 14,
      card_date_font_size: 11,
      card_caption_font_size: 11,
      carousel_cols: 3,
      carousel_rows: 2,
      carousel_image_height_pct: 60,
    },
  },
  {
    id: "warm-earth",
    name: "Terra Quente",
    description: "Tons terrosos e dourados, elegante e acolhedor",
    thumbnail: "🌿",
    settings: {
      background_color: "#1A1612",
      accent_color: "#D4A853",
      title_color: "#F5E6CC",
      subtitle_color: "#A89070",
      margin_size: 60,
      title_font_size: 34,
      subtitle_font_size: 17,
      card_image_width_pct: 42,
      card_font_size: 15,
      card_date_font_size: 12,
      card_caption_font_size: 11,
      carousel_cols: 4,
      carousel_rows: 2,
      carousel_image_height_pct: 65,
    },
  },
  {
    id: "neon-pop",
    name: "Neon Pop",
    description: "Visual vibrante com rosa neon e fundo escuro",
    thumbnail: "⚡",
    settings: {
      background_color: "#0D0D0D",
      accent_color: "#FF3E8A",
      title_color: "#FFFFFF",
      subtitle_color: "#999999",
      margin_size: 50,
      title_font_size: 36,
      subtitle_font_size: 18,
      card_image_width_pct: 50,
      card_font_size: 16,
      card_date_font_size: 13,
      card_caption_font_size: 12,
      carousel_cols: 3,
      carousel_rows: 2,
      carousel_image_height_pct: 70,
    },
  },
  {
    id: "ocean-calm",
    name: "Ocean Calm",
    description: "Azul profundo com acentos turquesa, sereno",
    thumbnail: "🌊",
    settings: {
      background_color: "#0C1929",
      accent_color: "#00BFA5",
      title_color: "#E8F4F8",
      subtitle_color: "#7BA7C2",
      margin_size: 65,
      title_font_size: 30,
      subtitle_font_size: 16,
      card_image_width_pct: 45,
      card_font_size: 14,
      card_date_font_size: 12,
      card_caption_font_size: 11,
      carousel_cols: 4,
      carousel_rows: 2,
      carousel_image_height_pct: 65,
    },
  },
  {
    id: "soft-blush",
    name: "Soft Blush",
    description: "Rosa suave com fundo claro, feminino e delicado",
    thumbnail: "🌸",
    settings: {
      background_color: "#FFF5F5",
      accent_color: "#E8596E",
      title_color: "#2D1B1E",
      subtitle_color: "#8B6B6F",
      margin_size: 70,
      title_font_size: 28,
      subtitle_font_size: 16,
      card_image_width_pct: 48,
      card_font_size: 13,
      card_date_font_size: 11,
      card_caption_font_size: 11,
      carousel_cols: 3,
      carousel_rows: 2,
      carousel_image_height_pct: 60,
    },
  },
];
