drop policy "client_cycle_stages_insert_combined" on public.client_cycle_stages;
create policy "client_cycle_stages_insert_combined" on public.client_cycle_stages
  for insert to public
  with check ((has_role((select auth.uid()), 'admin'::app_role) or ((select auth.uid()) is not null and stage = any (array['captacao'::stage_type, 'edicao_videos'::stage_type, 'planejamento'::stage_type, 'design'::stage_type, 'revisao'::stage_type, 'pdf'::stage_type, 'entrega'::stage_type, 'alteracoes'::stage_type, 'agendamento'::stage_type]) and exists (select 1 from client_cycles cc where cc.id = client_cycle_stages.cycle_id and cc.due_date = make_date(cc.year, cc.month, (select public.current_magic_number_day())) and cc.month >= 1 and cc.month <= 12 and cc.year >= 2000 and cc.year <= 2100))) and agency_id = (select public.current_agency_id()));

drop policy "client_cycle_stages_update_combined" on public.client_cycle_stages;
create policy "client_cycle_stages_update_combined" on public.client_cycle_stages
  for update to public
  using ((has_role((select auth.uid()), 'admin'::app_role) or ((select auth.uid()) is not null and stage = any (array['captacao'::stage_type, 'edicao_videos'::stage_type, 'planejamento'::stage_type, 'design'::stage_type, 'revisao'::stage_type, 'pdf'::stage_type, 'entrega'::stage_type, 'alteracoes'::stage_type, 'agendamento'::stage_type]) and exists (select 1 from client_cycles cc where cc.id = client_cycle_stages.cycle_id and cc.due_date = make_date(cc.year, cc.month, (select public.current_magic_number_day())) and cc.month >= 1 and cc.month <= 12 and cc.year >= 2000 and cc.year <= 2100))) and agency_id = (select public.current_agency_id()))
  with check ((has_role((select auth.uid()), 'admin'::app_role) or ((select auth.uid()) is not null and stage = any (array['captacao'::stage_type, 'edicao_videos'::stage_type, 'planejamento'::stage_type, 'design'::stage_type, 'revisao'::stage_type, 'pdf'::stage_type, 'entrega'::stage_type, 'alteracoes'::stage_type, 'agendamento'::stage_type]) and exists (select 1 from client_cycles cc where cc.id = client_cycle_stages.cycle_id and cc.due_date = make_date(cc.year, cc.month, (select public.current_magic_number_day())) and cc.month >= 1 and cc.month <= 12 and cc.year >= 2000 and cc.year <= 2100))) and agency_id = (select public.current_agency_id()));
